Dhyara: dhyara::xqueue< MessageT, Capacity > Class Template Reference
dhyara::xqueue< MessageT, Capacity > Class Template Reference
Creates a FreeRTOS queue.
#include <xqueue.h>
Public Member Functions
xqueue ()
construct a queue
bool en (const MessageT &msg, std::size_t ticks=0)
enqueue a value to the queue
bool overwrite (const MessageT &msg)
enqueue a value to the queue, if the queue is full overwrites the last
template<typename F >
void de (F fnc, std::size_t ticks=0xffffffffUL)
Receive loop using a function as callback.
MessageT de (std::size_t ticks=0xffffffffUL)
Receive a message and return.
bool de (MessageT &msg, std::size_t ticks=0xffffffffUL)
Receives a message into the refered value from the queue.
MessageT peek (std::size_t ticks=0xffffffffUL)
Peeks a message and return.
bool peek (MessageT &msg, std::size_t ticks=0xffffffffUL)
Peeks a message into the refered value from the queue.
UBaseType_t size ()
Return the number of messages stored in a queue.
std::uint32_t count () const
Returns the number of messages stored in the queue without making any FreeRTOS call.
UBaseType_t free ()
Return the number of free spaces in a queue.
bool empty ()
Check whether the queue is empty or not.
Detailed Description
template<typename MessageT, std::uint32_t Capacity>
class dhyara::xqueue< MessageT, Capacity >
Creates a FreeRTOS queue.
Definition at line 25 of file xqueue.h.
Constructor & Destructor Documentation
xqueue()
template<typename MessageT , std::uint32_t Capacity> dhyara::xqueue< MessageT, Capacity >::xqueue () inline
construct a queue
Definition at line 33 of file xqueue.h.
Member Function Documentation
count()
template<typename MessageT , std::uint32_t Capacity> std::uint32_t dhyara::xqueue< MessageT, Capacity >::count () const inline
Returns the number of messages stored in the queue without making any FreeRTOS call.
Definition at line 136 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::count().
de() [1/3]
template<typename MessageT , std::uint32_t Capacity> template<typename F > void dhyara::xqueue< MessageT, Capacity >::de (F fnc, std::size_t ticks = 0xffffffffUL) inline
Receive loop using a function as callback.
Parameters
fnc The callback to be called with the received messages.
ticks The maximum amount of time the task should block waiting for an item to receive should the queue be empty at the time of the call.
Definition at line 66 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::dequeue(), dhyara::network_fifo< dhyara::queue_size >::loop(), and dhyara::watcher< char >::watch().
de() [2/3]
template<typename MessageT , std::uint32_t Capacity> bool dhyara::xqueue< MessageT, Capacity >::de (MessageT & msg, std::size_t ticks = 0xffffffffUL) inline
Receives a message into the refered value from the queue.
Returns success value
Parameters
msg Reference to message, where the received message will be copied to.
ticks The maximum amount of time the task should block waiting for an item to receive should the queue be empty at the time of the call.
MessageT msg;
while(xq.de(msg, ticks)){
     process(msg);
}
Definition at line 95 of file xqueue.h.
de() [3/3]
template<typename MessageT , std::uint32_t Capacity> MessageT dhyara::xqueue< MessageT, Capacity >::de (std::size_t ticks = 0xffffffffUL) inline
Receive a message and return.
Parameters
ticks The maximum amount of time the task should block waiting for an item to receive should the queue be empty at the time of the call.
Definition at line 77 of file xqueue.h.
empty()
template<typename MessageT , std::uint32_t Capacity> bool dhyara::xqueue< MessageT, Capacity >::empty () inline
Check whether the queue is empty or not.
Definition at line 150 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::empty().
en()
template<typename MessageT , std::uint32_t Capacity> bool dhyara::xqueue< MessageT, Capacity >::en (const MessageT & msg, std::size_t ticks = 0) inline
enqueue a value to the queue
Parameters
msg The message to be enqueued.
ticks The maximum amount of time the task should block waiting for space to become available on the queue, should it already be full.
Definition at line 41 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::enqueue().
free()
template<typename MessageT , std::uint32_t Capacity> UBaseType_t dhyara::xqueue< MessageT, Capacity >::free () inline
Return the number of free spaces in a queue.
Definition at line 143 of file xqueue.h.
overwrite()
template<typename MessageT , std::uint32_t Capacity> bool dhyara::xqueue< MessageT, Capacity >::overwrite (const MessageT & msg) inline
enqueue a value to the queue, if the queue is full overwrites the last
Warning
intended to be used on queues with single element
Parameters
msg The message to be enqueued.
Definition at line 53 of file xqueue.h.
Referenced by dhyara::watcher< char >::notify().
peek() [1/2]
template<typename MessageT , std::uint32_t Capacity> bool dhyara::xqueue< MessageT, Capacity >::peek (MessageT & msg, std::size_t ticks = 0xffffffffUL) inline
Peeks a message into the refered value from the queue.
Returns success value. peek(0) peeks a message immediately if at least one exists and returns true, otherwise returns false.
Parameters
msg out parameter to put the message
ticks The maximum amount of time the task should block waiting for an item to receive should the queue be empty at the time of the call.
MessageT msg;
while(xq.peek(msg, ticks)){
     process(msg);
}
Definition at line 122 of file xqueue.h.
peek() [2/2]
template<typename MessageT , std::uint32_t Capacity> MessageT dhyara::xqueue< MessageT, Capacity >::peek (std::size_t ticks = 0xffffffffUL) inline
Peeks a message and return.
peek(0) returns a message immediately if at least one exists, otherwise returns a default constructed empty message.
Parameters
ticks The maximum amount of time the task should block waiting for an item to receive should the queue be empty at the time of the call.
Definition at line 106 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::peek().
size()
template<typename MessageT , std::uint32_t Capacity> UBaseType_t dhyara::xqueue< MessageT, Capacity >::size () inline
Return the number of messages stored in a queue.
Definition at line 129 of file xqueue.h.
Referenced by dhyara::xqueue< char, 1 >::empty(), dhyara::network_fifo< dhyara::queue_size >::size(), and dhyara::watcher< char >::sleeping().
The documentation for this class was generated from the following file:
includes/dhyara/xqueue.h