Dhyara: dhyara::link Class Reference
dhyara::link Class Reference
Dhyara
Link is responsible for low level sending/receiving.
#include <link.h>
Classes
struct proxy
Public Member Functions
link ()
Construct.
void init ()
Initialize the medium.
template<typename PacketT >
bool send_local (const dhyara::address &addr, packets::type type, const PacketT &packet)
Sends a packet to an immediate neighbour directly in one hop.
template<typename PacketT >
bool send (const dhyara::address &addr, packets::type type, const PacketT &packet)
Sends a packet via the best intermediate node.
dhyara::neighbourhood & neighbours ()
immediate neighbourhood
dhyara::universe & universe ()
The known universe.
dhyara::routing & routes ()
routing table
const dhyara::address & address () const
local address
esp_err_t connect (const dhyara::address &target)
Associate with the target AP using the station interface.
Statistical
void reset (dhyara::packets::type type)
reset counter
std::size_t tx (dhyara::packets::type type) const
number of packets received for the given type
std::size_t rx (dhyara::packets::type type) const
number of packets recieved for the given type
std::int8_t max_rssi () const
Maximum rssi in the neighbourhood.
dhyara::delay_type lost () const
Duration for which the node has not heard anything from its neighbourhood (in us).
Actions
Associate Actions with a packet type and access the associated actions.
void install (dhyara::packets::type type, callback_type cb)
Associate an action with a packet type.
proxy operator[] (dhyara::packets::type type)
Conveniance function to install an action (associate an action with a packet type).
ESP Now callbacks
The functions that are supposed to be registered as callbacks to the underlying ESP Now subsystem.
Attention
These functions may not be called from the usercode. These are called by dhyara_espnow_init function.
void _esp_sent_cb (const uint8_t *target, esp_now_send_status_t status)
ESP Now Send Callback.
void _esp_rcvd_cb (const uint8_t *source, const uint8_t *data, int len)
Process raw data received.
Callbacks for RSSI
The functions that are supposed to be registered as callbacks to the underlying ESP Now subsystem.
Attention
These functions may not be called from the usercode. These are called by dhyara_espnow_init function.
void _esp_promiscous_rx_cb (void *buffer, wifi_promiscuous_pkt_type_t type)
Updates RSSI by using the frame headers received in the promiscous mode.
Tasks
The IO tasks are infinite loops that never returns.
Attention
This functions may not be called from the usercode. These are called by dhyara::network::start while creating FreeRTOS Tasks.
void start_rcv (std::size_t ticks=0xffffffffUL)
start receive loop never returns
void start_snd (std::size_t ticks=0xffffffffUL)
start receive loop never returns
Private Member Functions
void q_receive (const dhyara::address &address, const dhyara::frame &frame)
Process a received frame.
bool _transmit (const std::uint8_t *dest, const std::uint8_t *data, std::size_t len)
Send raw data to an immediate destination.
bool transmit (const dhyara::address &address, const dhyara::frame &frame)
Depending of the configuration of transmission queueing, Transmits/Enequeues a frame for sending to the given destination address in one hop.
Private Attributes
dhyara::frame _frame_rcv
Temporary buffer to hold the received frame which is then enqueued to _fifo.
fifo_type _fifo_rcv
Queue to manage the received frames.
xqueue_type _queue_snd
Queue to manage the frames to be sent.
dhyara::notifier _notifier
A single element queue to wake up sending task.
Detailed Description
Link is responsible for low level sending/receiving.
Attention
Usercode may not need to interact with dhyara::link directly unless there is a customization of the underlying communication protocol is required.
All received data should be forwarded to the link via _esp_sent_cb which wil then be processed through the installed actions (Actions).
dhyara::link medium; // A communication medium
dhyara::actions::acknowledgement acknowledgement(medium.local()); // Handler for acknowledgement packets
medium[dhyara::packets::type::acknowledgement] = acknowledgement;
// associate other actions ...
Internal Send Receive Mechanism
_esp_rcvd_cb has to be registered to the esp_now_register_send_cb() for send queueing. The sending and receiving tasks are never ending infinitie lops that dequeues the send and receive queue respectively. start_rcv and start_snd are used to create send and receive tasks by dhyara::network::start.
sending a frame is more complecated that receiving it. All overloads of dhyara::link::send ultimately calls dhyara::link::transmit. If Send Queuing is enabled (by default) then transmit queues the frame instead of actually transmitting it. Otherwise it transmit using dhyara::link::_transmit.
Definition at line 94 of file link.h.
Member Function Documentation
_esp_promiscous_rx_cb()
void dhyara::link::_esp_promiscous_rx_cb (void * buffer, wifi_promiscuous_pkt_type_t type)
Updates RSSI by using the frame headers received in the promiscous mode.
Attention
This function may not be called from the usercode. These are called by dhyara_espnow_init function.
This function is supposed by the callback passed to esp_wifi_set_promiscuous_rx_cb().
Parameters
buffer received data
type promiscous packet type
_esp_rcvd_cb()
void dhyara::link::_esp_rcvd_cb (const uint8_t * source, const uint8_t * data, int len)
Process raw data received.
Create a frame from the received data and passes that to queue for further procesing. Leaves wifi stack
Attention
This function may not be called from the usercode. These are called by dhyara_espnow_init function.
This function is supposed by the callback passed to esp_now_register_recv_cb().
Parameters
source source address
data raw data received
len length of the raw data
_esp_sent_cb()
void dhyara::link::_esp_sent_cb (const uint8_t * target, esp_now_send_status_t status)
ESP Now Send Callback.
Attention
This function may not be called from the usercode. These are called by dhyara_espnow_init function.
This function is supposed by the callback passed to esp_now_register_send_cb().
Parameters
target target address
status status
_transmit()
bool dhyara::link::_transmit (const std::uint8_t * dest, const std::uint8_t * data, std::size_t len) private
Send raw data to an immediate destination.
Called directly if transmission queueing is disabled. Otherwise called through start_snd
Parameters
dest destination
data pointer to raw data
len lenth of the data
install()
void dhyara::link::install (dhyara::packets::type type, callback_type cb)
Associate an action with a packet type.
The operator()() overload of that action will be called with the received packet.
Parameters
type packet type
cb The action
operator[]()
proxy dhyara::link::operator[] (dhyara::packets::type type) inline
Conveniance function to install an action (associate an action with a packet type).
dhyara::link medium;
dhyara::actions::beacon beacon(medium);
medium[dhyara::packets::type::beacon] = beacon;
Parameters
type packet type
Definition at line 228 of file link.h.
q_receive()
void dhyara::link::q_receive (const dhyara::address & address, const dhyara::frame & frame) private
Process a received frame.
Warning
should not be called directly. Supposed to be used as a callback.
Parameters
address immediate source address
frame frame
rx()
std::size_t dhyara::link::rx (dhyara::packets::type type) const
number of packets recieved for the given type
Parameters
type packet type
send()
template<typename PacketT > bool dhyara::link::send (const dhyara::address & addr, packets::type type, const PacketT & packet) inline
Sends a packet via the best intermediate node.
If the destination address is immediate neighbour then sends directly.
Parameters
addr target peer address
type packet type
packet packet object
Definition at line 148 of file link.h.
References dhyara::address::is_null(), dhyara::routing::next(), send_local(), and dhyara::routing::next_hop::via().
send_local()
template<typename PacketT > bool dhyara::link::send_local (const dhyara::address & addr, packets::type type, const PacketT & packet) inline
Sends a packet to an immediate neighbour directly in one hop.
Parameters
addr target peer address
type packet type
packet packet object
Definition at line 132 of file link.h.
References transmit(), and dhyara::write().
Referenced by send().
start_rcv()
void dhyara::link::start_rcv (std::size_t ticks = 0xffffffffUL)
start receive loop never returns
Attention
Usercode may not call this function directly. Supposed to be called by dhyara::network::start while creating FreeRTOS Task.
start_snd()
void dhyara::link::start_snd (std::size_t ticks = 0xffffffffUL)
start receive loop never returns
Attention
Only available is Send Queueing is enabled (enabled by default)
Usercode may not call this function directly. Supposed to be called by dhyara::network::start while creating FreeRTOS Task.
transmit()
bool dhyara::link::transmit (const dhyara::address & address, const dhyara::frame & frame) private
Depending of the configuration of transmission queueing, Transmits/Enequeues a frame for sending to the given destination address in one hop.
Attention
If Send Queueing is enabled (default) then, instead of sending the frame directly, it is enqueued to _queue_snd, and a notifier is notified about the pending frame. Another task is running start_snd which is woken up after receiving the notification. Once woken up, start_snd dequeues one frame from the _queue_snd and transmits using _transmit. Once a message is sent, The send callback _esp_sent_cb is called, which also notifies the notifier and wakes up start_snd. This ensures No two frames are sent in parellal.
If Send Queueing is disabled then the frame is sent immediately without waiting for the sent callback to be called for the previous transmission operation.
Parameters
address destination address
frame frame
Referenced by send_local().
tx()
std::size_t dhyara::link::tx (dhyara::packets::type type) const
number of packets received for the given type
Parameters
type packet type
The documentation for this class was generated from the following file:
includes/dhyara/link.h