Dhyara: /home/runner/work/dhyara/dhyara/includes/dhyara/frame.h File Reference
frame.h File Reference
#include <iostream>
#include "dhyara/packets/types.h"
#include "dhyara/packets/io.h"
Classes
struct dhyara::frame
A 250 bytes frame is defined by a 2 bytes header and 248 bytes payload.
Namespaces
dhyara
Typedefs
typedef std::uint8_t size_type
Functions
struct dhyara::frame dhyara::__attribute__ ((packed))
frame ()
Construct a frame that is supposed to contain a packet of unknown type.
frame (packets::type type)
Construct a frame that is supposed to contain a packet of the given type.
frame (packets::type type, std::size_t len)
Construct a frame of provided payload payload that is supposed to contain a packet of the given type.
bool valid () const
CHecks whether the frame is valid or not.
constexpr static std::uint8_t header_size ()
Sise of the header of the frame (2 bytes)
packets::type type () const
Packet type in the frame.
std::size_t length () const
Length of the frame.
std::size_t size () const
Size of the frame.
void clear ()
Clears the frame, zerofills the internal buffer.
template<typename PacketT >
static frame create (packets::type type, const PacketT &packet)
Create a frame from a packet and a packet type.
template<typename PacketT >
static frame * create_new (packets::type type, const PacketT &packet)
Creates a frame on heap with teh given packet and a packet type.
Variables
packets::type _type
size_type _length
std::uint8_t _buffer [248]
Typedef Documentation
size_type
typedef std::uint8_t size_type
Definition at line 2 of file frame.h.
Function Documentation
clear()
void __attribute__::clear () inline
Clears the frame, zerofills the internal buffer.
Definition at line 58 of file frame.h.
create()
template<typename PacketT > static frame __attribute__::create (packets::type type, const PacketT & packet) static
Create a frame from a packet and a packet type.
Returns
returns the created frame
Definition at line 69 of file frame.h.
create_new()
template<typename PacketT > static frame* __attribute__::create_new (packets::type type, const PacketT & packet) static
Creates a frame on heap with teh given packet and a packet type.
Returns
returns pointer to the newly created frame
Definition at line 79 of file frame.h.
References dhyara::frame::_buffer, dhyara::frame::_length, dhyara::frame::_type, and dhyara::packets::unknown.
frame() [1/3]
__attribute__::frame () inline
Construct a frame that is supposed to contain a packet of unknown type.
Definition at line 11 of file frame.h.
Referenced by dhyara::link::send_local().
frame() [2/3]
__attribute__::frame (packets::type type) inline
Construct a frame that is supposed to contain a packet of the given type.
Parameters
type type of the packet
Definition at line 18 of file frame.h.
frame() [3/3]
__attribute__::frame (packets::type type, std::size_t len) inline
Construct a frame of provided payload payload that is supposed to contain a packet of the given type.
Parameters
type packet type
length length of the frame
Definition at line 26 of file frame.h.
header_size()
constexpr static std::uint8_t __attribute__::header_size () static constexpr
Sise of the header of the frame (2 bytes)
Definition at line 40 of file frame.h.
length()
std::uint8_t length () const inline
Length of the frame.
Definition at line 49 of file frame.h.
Referenced by dhyara::read(), and dhyara::serialization< PacketT >::read().
size()
std::size_t size () const inline
Size of the frame.
Definition at line 53 of file frame.h.
type()
packets::type __attribute__::type () const inline
Packet type in the frame.
Definition at line 45 of file frame.h.
Referenced by dhyara::link::operator[](), dhyara::link::send(), and dhyara::link::send_local().
valid()
bool __attribute__::valid () const inline
CHecks whether the frame is valid or not.
Definition at line 33 of file frame.h.
Variable Documentation
_buffer
std::uint8_t _buffer[248]
Definition at line 6 of file frame.h.
_length
std::uint8_t _length
Definition at line 5 of file frame.h.
_type
packets::type _type
Definition at line 4 of file frame.h.