Dhyara: IO
IO
Packets
Packets Input Output.
Classes
struct dhyara::serialization< PacketT >
serialize a packet
struct dhyara::utils::printer
print packets
Functions
template<typename PacketT , typename OutIt >
OutIt dhyara::write (const PacketT &packet, OutIt output)
write a packet
template<typename PacketT , typename InIt >
InIt dhyara::read (PacketT &packet, InIt input, std::size_t length=0)
read into a packet
Detailed Description
Packets Input Output.
Function Documentation
read()
template<typename PacketT , typename InIt > InIt dhyara::read (PacketT & packet, InIt input, std::size_t length = 0)
read into a packet
Definition at line 30 of file io.h.
References length(), packet(), and dhyara::serialization< PacketT >::read().
Referenced by dhyara::actions::action< echo_request, dhyara::packets::echo_request >::operator()().
write()
template<typename PacketT , typename OutIt > OutIt dhyara::write (const PacketT & packet, OutIt output)
write a packet
Definition at line 21 of file io.h.
References packet(), and dhyara::serialization< PacketT >::write().
Referenced by dhyara::frame::create(), dhyara::frame::create_new(), and dhyara::link::send_local().