Dhyara: /home/runner/work/dhyara/dhyara/includes/dhyara/packets/echo_reply.h File Reference
echo_reply.h File Reference
#include <array>
#include <cstdint>
#include "dhyara/peer.h"
#include "esp_timer.h"
Classes
struct dhyara::packets::echo_reply
An echo reply.
Namespaces
dhyara
dhyara::packets
Typedefs
typedef std::array< std::uint8_t, 6 > raw_address_type
Functions
struct dhyara::packets::acknowledgement dhyara::packets::__attribute__ ((packed))
echo_reply ()
Construct an echo reply to null destination originating from null destination on current time.
echo_reply (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint32_t seq=0, std::uint64_t time=esp_timer_get_time(), std::uint8_t ttl=255)
Construct an echo reply to the target originating from the source with the provided sequence number and time.
std::size_t size () const
Size of the packet.
std::uint64_t time () const
Time in the packet.
std::uint32_t seq () const
Sequence number in teh packet.
std::uint8_t ttl () const
TTL value.
dhyara::peer::address target () const
target address
dhyara::peer::address source () const
source address
Variables
raw_address_type _target
raw_address_type _source
std::uint32_t _seq
std::uint64_t _time
std::uint8_t _ttl
Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> raw_address_type
Definition at line 2 of file echo_reply.h.
Function Documentation
echo_reply() [1/2]
__attribute__::echo_reply () inline
Construct an echo reply to null destination originating from null destination on current time.
Definition at line 13 of file echo_reply.h.
echo_reply() [2/2]
__attribute__::echo_reply (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint32_t seq = 0, std::uint64_t time = esp_timer_get_time(), std::uint8_t ttl = 255) inline
Construct an echo reply to the target originating from the source with the provided sequence number and time.
Parameters
target the target mac address
source the originating mac address
seq the sequence number of this ICMP request
time the time in the ICMP request (defaults to current time)
Definition at line 24 of file echo_reply.h.
seq()
std::uint32_t __attribute__::seq () const inline
Sequence number in teh packet.
Definition at line 40 of file echo_reply.h.
size()
std::size_t __attribute__::size () const inline
Size of the packet.
Definition at line 32 of file echo_reply.h.
source()
dhyara::peer::address __attribute__::source () const inline
source address
Definition at line 52 of file echo_reply.h.
target()
dhyara::peer::address __attribute__::target () const inline
target address
Definition at line 48 of file echo_reply.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and dhyara::packets::echo_reply::target().
time()
std::uint64_t __attribute__::time () const inline
Time in the packet.
Definition at line 36 of file echo_reply.h.
ttl()
std::uint8_t __attribute__::ttl () const inline
TTL value.
Definition at line 44 of file echo_reply.h.
Variable Documentation
_seq
std::uint32_t _seq
Definition at line 6 of file echo_reply.h.
_source
raw_address_type _source
Definition at line 5 of file echo_reply.h.
_target
raw_address_type _target
Definition at line 4 of file echo_reply.h.
_time
std::uint64_t _time
Definition at line 7 of file echo_reply.h.
_ttl
std::uint8_t _ttl
Definition at line 8 of file echo_reply.h.