Dhyara: /home/runner/work/dhyara/dhyara/includes/dhyara/packets/chunk.h File Reference
chunk.h File Reference
#include <array>
#include <cstdint>
#include "dhyara/peer.h"
Classes
struct dhyara::packets::chunk
Chunk of a variable sized data.
struct dhyara::packets::chunk::header
Header in the chunk.
struct header
Header in the chunk.
Namespaces
dhyara
dhyara::packets
Typedefs
typedef std::array< std::uint8_t, 6 > raw_address_type
typedef std::array< std::uint8_t, capacity > buffer_type
typedef buffer_type::const_iterator const_iterator_type
Enumerations
enum { capacity = 250 - (sizeof(header) +2) }
Functions
header ()
header (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending=0)
std::uint8_t length () const
std::size_t size () const
dhyara::peer::address target () const
dhyara::peer::address source () const
std::uint8_t packet () const
std::uint8_t pending () const
bool is_last () const
struct dhyara::packets::acknowledgement dhyara::packets::__attribute__ ((packed))
struct header __attribute__ ((packed))
chunk ()
template<typename InputIt >
chunk (const dhyara::peer::address &target, const dhyara::peer::address &source, InputIt begin, std::uint8_t length, std::uint8_t packet, std::uint8_t pending=0)
template<typename OutIt >
OutIt copy (OutIt it)
const_iterator_type begin () const
const_iterator_type end () const
Variables
raw_address_type _target
raw_address_type _source
std::uint8_t _length
std::uint8_t _packet
std::uint8_t _pending
enum { ... } __attribute__
header _header
buffer_type _buffer
Typedef Documentation
buffer_type
typedef std::array<std::uint8_t, capacity> buffer_type
Definition at line 30 of file chunk.h.
const_iterator_type
typedef buffer_type::const_iterator const_iterator_type
Definition at line 31 of file chunk.h.
raw_address_type
typedef std::array<std::uint8_t, 6> raw_address_type
Definition at line 2 of file chunk.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
capacity
Definition at line 29 of file chunk.h.
Function Documentation
__attribute__()
struct header __attribute__::__attribute__ ((packed))
begin()
const_iterator_type __attribute__::begin () const inline
Definition at line 52 of file chunk.h.
References dhyara::packets::chunk::capacity, and dhyara::packets::chunk::header().
Referenced by dhyara::packets::data::data(), dhyara::packets::data::fill(), and dhyara::network::send().
chunk() [1/2]
__attribute__::chunk () inline
Definition at line 36 of file chunk.h.
chunk() [2/2]
template<typename InputIt > __attribute__::chunk (const dhyara::peer::address & target, const dhyara::peer::address & source, InputIt begin, std::uint8_t length, std::uint8_t packet, std::uint8_t pending = 0) inline
Definition at line 40 of file chunk.h.
copy()
template<typename OutIt > OutIt __attribute__::copy (OutIt it)
Definition at line 47 of file chunk.h.
References dhyara::packets::chunk::header::_packet.
Referenced by dhyara::packets::chunk::chunk(), dhyara::packets::chunk::copy(), dhyara::packets::data::copy(), dhyara::peer_address::copy(), dhyara::packets::data::fill(), dhyara::serialization< PacketT >::read(), and dhyara::serialization< PacketT >::write().
end()
const_iterator_type __attribute__::end () const inline
Definition at line 53 of file chunk.h.
Referenced by dhyara::packets::data::data(), dhyara::packets::data::fill(), dhyara::serialization< PacketT >::read(), and dhyara::network::send().
header() [1/2]
const header & header ()
Definition at line 32 of file chunk.h.
header() [2/2]
header (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending = 0) inline
Definition at line 33 of file chunk.h.
is_last()
bool is_last () const inline
Definition at line 44 of file chunk.h.
References dhyara::packets::chunk::header::header().
length()
std::uint8_t __attribute__::length () const inline
Definition at line 38 of file chunk.h.
packet()
std::uint8_t packet () const inline
Definition at line 42 of file chunk.h.
Referenced by dhyara::frame::create(), dhyara::frame::create_new(), dhyara::actions::action< echo_request, dhyara::packets::echo_request >::operator()(), dhyara::read(), dhyara::serialization< PacketT >::read(), dhyara::serialization< packets::beacon >::read(), dhyara::link::send(), dhyara::link::send_local(), dhyara::write(), dhyara::serialization< PacketT >::write(), and dhyara::serialization< packets::beacon >::write().
pending()
std::uint8_t pending () const inline
Definition at line 43 of file chunk.h.
References dhyara::packets::chunk::header::_length.
size()
std::size_t __attribute__::size () const inline
Definition at line 39 of file chunk.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and dhyara::packets::chunk::header::target().
source()
dhyara::peer::address source () const inline
Definition at line 41 of file chunk.h.
target()
dhyara::peer::address target () const inline
Definition at line 40 of file chunk.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and dhyara::packets::chunk::header::source().
Referenced by dhyara::network::send().
Variable Documentation
__attribute__
enum { ... } __attribute__
_buffer
buffer_type _buffer
Definition at line 34 of file chunk.h.
_header
header _header
Definition at line 33 of file chunk.h.
_length
std::uint8_t _length
Definition at line 28 of file chunk.h.
_packet
std::uint8_t _packet
Definition at line 29 of file chunk.h.
_pending
std::uint8_t _pending
Definition at line 30 of file chunk.h.
_source
raw_address_type _source
Definition at line 27 of file chunk.h.
_target
raw_address_type _target
Definition at line 26 of file chunk.h.