Dhyara: dhyara::serialization< PacketT > Struct Template Reference
dhyara::serialization< PacketT > Struct Template Reference
Packets » IO
serialize a packet
#include <serialization.h>
Static Public Member Functions
template<typename OutIt >
static OutIt write (const packet_type &packet, OutIt output)
serialize a packet and write to the output iterator
template<typename InIt >
static InIt read (packet_type &packet, InIt input, std::size_t length)
deserializes a packet by reading length bytes from the input iterator
Detailed Description
template<typename PacketT>
struct dhyara::serialization< PacketT >
serialize a packet
Definition at line 22 of file serialization.h.
Member Function Documentation
read()
template<typename PacketT > template<typename InIt > static InIt dhyara::serialization< PacketT >::read (packet_type & packet, InIt input, std::size_t length) inline static
deserializes a packet by reading length bytes from the input iterator
Parameters
packet the packet to compose
input the input iterator
length length of the input
Definition at line 45 of file serialization.h.
Referenced by dhyara::read().
write()
template<typename PacketT > template<typename OutIt > static OutIt dhyara::serialization< PacketT >::write (const packet_type & packet, OutIt output) inline static
serialize a packet and write to the output iterator
Parameters
packet the packet to be serialized
output the output iterator
Definition at line 32 of file serialization.h.
Referenced by dhyara::frame::copy_from(), and dhyara::write().
The documentation for this struct was generated from the following file:
includes/dhyara/packets/serialization.h