Dhyara: dhyara::packets::delivered Struct Reference
dhyara::packets::delivered Struct Reference
Packets
Delivery report for a complete data packet, only sent if all of its chunks are successfully delivered.
#include <delivered.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
delivered ()
Construct a delivery report with source and target set to null address and packet id is set to 0.
delivered (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint8_t packet)
Construct a delivery report using target, source address and the packet id in the target.
std::size_t size () const
Siez of the delivery report.
dhyara::peer::address target () const
Target.
dhyara::peer::address source () const
Source.
std::uint8_t packet () const
packet id
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint8_t _packet
Detailed Description
Delivery report for a complete data packet, only sent if all of its chunks are successfully delivered.
A delivery report contains a packet attribute to relate the data against which the delivery report is issued.
Definition at line 24 of file delivered.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::delivered::raw_address_type
Definition at line 25 of file delivered.h.
Constructor & Destructor Documentation
delivered() [1/2]
dhyara::packets::delivered::delivered () inline
Construct a delivery report with source and target set to null address and packet id is set to 0.
Definition at line 34 of file delivered.h.
Referenced by size().
delivered() [2/2]
dhyara::packets::delivered::delivered (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint8_t packet) inline
Construct a delivery report using target, source address and the packet id in the target.
Parameters
target the target address
source the source address
packet the packet id in the data
Definition at line 41 of file delivered.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and target().
Member Function Documentation
packet()
std::uint8_t dhyara::packets::delivered::packet () const inline
packet id
Definition at line 61 of file delivered.h.
References _packet.
size()
std::size_t dhyara::packets::delivered::size () const inline
Siez of the delivery report.
Definition at line 49 of file delivered.h.
References delivered().
source()
dhyara::peer::address dhyara::packets::delivered::source () const inline
Source.
Definition at line 57 of file delivered.h.
References _source.
target()
dhyara::peer::address dhyara::packets::delivered::target () const inline
Target.
Definition at line 53 of file delivered.h.
References _target.
Referenced by delivered().
Member Data Documentation
_packet
std::uint8_t dhyara::packets::delivered::_packet
Definition at line 29 of file delivered.h.
Referenced by packet().
_source
raw_address_type dhyara::packets::delivered::_source
Definition at line 28 of file delivered.h.
Referenced by source().
_target
raw_address_type dhyara::packets::delivered::_target
Definition at line 27 of file delivered.h.
Referenced by target().
The documentation for this struct was generated from the following file:
includes/dhyara/packets/delivered.h