Dhyara: dhyara::packets::echo_lost Struct Reference
dhyara::packets::echo_lost Struct Reference
Packets
Echo lost packet.
#include <echo_lost.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
echo_lost ()
Construct an echo lost to null destination originating from null destination on current time.
echo_lost (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint32_t seq=0, std::uint64_t time=0)
Construct an echo lost to the target originating from the source with the provided sequence number and time.
std::size_t size () const
Size of the packet.
std::uint64_t time () const
Time in the packet.
std::uint32_t seq () const
Sequence number.
dhyara::peer::address target () const
Target address.
dhyara::peer::address source () const
Source address.
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint32_t _seq
std::uint64_t _time
Detailed Description
Echo lost packet.
Definition at line 26 of file echo_lost.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::echo_lost::raw_address_type
Definition at line 27 of file echo_lost.h.
Constructor & Destructor Documentation
echo_lost() [1/2]
dhyara::packets::echo_lost::echo_lost () inline
Construct an echo lost to null destination originating from null destination on current time.
Definition at line 37 of file echo_lost.h.
Referenced by size().
echo_lost() [2/2]
dhyara::packets::echo_lost::echo_lost (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint32_t seq = 0, std::uint64_t time = 0) inline
Construct an echo lost to the target originating from the source with the provided sequence number and time.
Parameters
target the target mac address
source the originating mac address
seq the sequence number of this ICMP request
time the time in the ICMP request (defaults to current time)
Definition at line 49 of file echo_lost.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and target().
Member Function Documentation
seq()
std::uint32_t dhyara::packets::echo_lost::seq () const inline
Sequence number.
Definition at line 65 of file echo_lost.h.
References _seq.
size()
std::size_t dhyara::packets::echo_lost::size () const inline
Size of the packet.
Definition at line 57 of file echo_lost.h.
References echo_lost().
source()
dhyara::peer::address dhyara::packets::echo_lost::source () const inline
Source address.
Definition at line 73 of file echo_lost.h.
References _source.
target()
dhyara::peer::address dhyara::packets::echo_lost::target () const inline
Target address.
Definition at line 69 of file echo_lost.h.
References _target.
Referenced by echo_lost().
time()
std::uint64_t dhyara::packets::echo_lost::time () const inline
Time in the packet.
Definition at line 61 of file echo_lost.h.
References _time.
Member Data Documentation
_seq
std::uint32_t dhyara::packets::echo_lost::_seq
Definition at line 31 of file echo_lost.h.
Referenced by seq().
_source
raw_address_type dhyara::packets::echo_lost::_source
Definition at line 30 of file echo_lost.h.
Referenced by source().
_target
raw_address_type dhyara::packets::echo_lost::_target
Definition at line 29 of file echo_lost.h.
Referenced by target().
_time
std::uint64_t dhyara::packets::echo_lost::_time
Definition at line 32 of file echo_lost.h.
Referenced by time().
The documentation for this struct was generated from the following file:
dhyara/packets/echo_lost.h