Dhyara: dhyara::packets::chunk::header Struct Reference
dhyara::packets::chunk::header Struct Reference
Header in the chunk.
#include <chunk.h>
Public Member Functions
header ()
header (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending=0)
std::uint8_t length () const
std::size_t size () const
dhyara::peer::address target () const
dhyara::peer::address source () const
std::uint8_t packet () const
std::uint8_t pending () const
bool is_last () const
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint8_t _length
std::uint8_t _packet
std::uint8_t _pending
Detailed Description
Header in the chunk.
Definition at line 30 of file chunk.h.
Constructor & Destructor Documentation
header() [1/2]
dhyara::packets::chunk::header::header () inline
Definition at line 37 of file chunk.h.
Referenced by size().
header() [2/2]
dhyara::packets::chunk::header::header (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending = 0) inline
Definition at line 38 of file chunk.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and target().
Member Function Documentation
is_last()
bool dhyara::packets::chunk::header::is_last () const inline
Definition at line 49 of file chunk.h.
References pending().
length()
std::uint8_t dhyara::packets::chunk::header::length () const inline
Definition at line 43 of file chunk.h.
References _length.
Referenced by dhyara::packets::chunk::chunk(), dhyara::packets::chunk::copy(), and dhyara::packets::chunk::end().
packet()
std::uint8_t dhyara::packets::chunk::header::packet () const inline
Definition at line 47 of file chunk.h.
References _packet.
Referenced by dhyara::packets::chunk::packet().
pending()
std::uint8_t dhyara::packets::chunk::header::pending () const inline
Definition at line 48 of file chunk.h.
References _pending.
Referenced by is_last(), and dhyara::packets::chunk::pending().
size()
std::size_t dhyara::packets::chunk::header::size () const inline
Definition at line 44 of file chunk.h.
References header().
source()
dhyara::peer::address dhyara::packets::chunk::header::source () const inline
Definition at line 46 of file chunk.h.
References _source.
Referenced by dhyara::packets::chunk::source().
target()
dhyara::peer::address dhyara::packets::chunk::header::target () const inline
Definition at line 45 of file chunk.h.
References _target.
Referenced by header(), and dhyara::packets::chunk::target().
Member Data Documentation
_length
std::uint8_t dhyara::packets::chunk::header::_length
Definition at line 33 of file chunk.h.
Referenced by length(), and dhyara::packets::chunk::length().
_packet
std::uint8_t dhyara::packets::chunk::header::_packet
Definition at line 34 of file chunk.h.
Referenced by packet().
_pending
std::uint8_t dhyara::packets::chunk::header::_pending
Definition at line 35 of file chunk.h.
Referenced by pending().
_source
raw_address_type dhyara::packets::chunk::header::_source
Definition at line 32 of file chunk.h.
Referenced by source().
_target
raw_address_type dhyara::packets::chunk::header::_target
Definition at line 31 of file chunk.h.
Referenced by target().
The documentation for this struct was generated from the following file:
dhyara/packets/chunk.h