Dhyara: dhyara::packets::echo_reply Struct Reference
dhyara::packets::echo_reply Struct Reference
Packets
An echo reply.
#include <echo_reply.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
echo_reply ()
Construct an echo reply to null destination originating from null destination on current time.
echo_reply (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint32_t seq=0, std::uint64_t time=esp_timer_get_time(), std::uint8_t ttl=255)
Construct an echo reply to the target originating from the source with the provided sequence number and time.
std::size_t size () const
Size of the packet.
std::uint64_t time () const
Time in the packet.
std::uint32_t seq () const
Sequence number in teh packet.
std::uint8_t ttl () const
TTL value.
dhyara::peer::address target () const
target address
dhyara::peer::address source () const
source address
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint32_t _seq
std::uint64_t _time
std::uint8_t _ttl
Detailed Description
An echo reply.
Definition at line 25 of file echo_reply.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::echo_reply::raw_address_type
Definition at line 26 of file echo_reply.h.
Constructor & Destructor Documentation
echo_reply() [1/2]
dhyara::packets::echo_reply::echo_reply () inline
Construct an echo reply to null destination originating from null destination on current time.
Definition at line 37 of file echo_reply.h.
Referenced by size().
echo_reply() [2/2]
dhyara::packets::echo_reply::echo_reply (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint32_t seq = 0, std::uint64_t time = esp_timer_get_time(), std::uint8_t ttl = 255) inline
Construct an echo reply to the target originating from the source with the provided sequence number and time.
Parameters
target the target mac address
source the originating mac address
seq the sequence number of this ICMP request
time the time in the ICMP request (defaults to current time)
ttl Time to Live (number of hops to live)
Definition at line 49 of file echo_reply.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and target().
Member Function Documentation
seq()
std::uint32_t dhyara::packets::echo_reply::seq () const inline
Sequence number in teh packet.
Definition at line 65 of file echo_reply.h.
References _seq.
size()
std::size_t dhyara::packets::echo_reply::size () const inline
Size of the packet.
Definition at line 57 of file echo_reply.h.
References echo_reply().
source()
dhyara::peer::address dhyara::packets::echo_reply::source () const inline
source address
Definition at line 77 of file echo_reply.h.
References _source.
target()
dhyara::peer::address dhyara::packets::echo_reply::target () const inline
target address
Definition at line 73 of file echo_reply.h.
References _target.
Referenced by echo_reply().
time()
std::uint64_t dhyara::packets::echo_reply::time () const inline
Time in the packet.
Definition at line 61 of file echo_reply.h.
References _time.
ttl()
std::uint8_t dhyara::packets::echo_reply::ttl () const inline
TTL value.
Definition at line 69 of file echo_reply.h.
References _ttl.
Member Data Documentation
_seq
std::uint32_t dhyara::packets::echo_reply::_seq
Definition at line 30 of file echo_reply.h.
Referenced by seq().
_source
raw_address_type dhyara::packets::echo_reply::_source
Definition at line 29 of file echo_reply.h.
Referenced by source().
_target
raw_address_type dhyara::packets::echo_reply::_target
Definition at line 28 of file echo_reply.h.
Referenced by target().
_time
std::uint64_t dhyara::packets::echo_reply::_time
Definition at line 31 of file echo_reply.h.
Referenced by time().
_ttl
std::uint8_t dhyara::packets::echo_reply::_ttl
Definition at line 32 of file echo_reply.h.
Referenced by ttl().
The documentation for this struct was generated from the following file:
includes/dhyara/packets/echo_reply.h