Dhyara: dhyara::message Struct Reference
dhyara::message Struct Reference
Envelop for both to be sent and has been received messages.
#include <xqueue.h>
Public Member Functions
message ()
message (const dhyara::peer_address &a, const dhyara::frame &f)
void clear ()
bool valid () const
Public Attributes
dhyara::peer_address address
dhyara::frame frame
Detailed Description
Envelop for both to be sent and has been received messages.
Definition at line 213 of file xqueue.h.
Constructor & Destructor Documentation
message() [1/2]
dhyara::message::message () inline
Definition at line 214 of file xqueue.h.
message() [2/2]
dhyara::message::message (const dhyara::peer_address & a, const dhyara::frame & f) inline
Definition at line 215 of file xqueue.h.
Member Function Documentation
clear()
void dhyara::message::clear () inline
Definition at line 217 of file xqueue.h.
References address, dhyara::frame::clear(), and dhyara::peer_address::null().
Referenced by dhyara::network_fifo< dhyara::queue_size >::loop().
valid()
bool dhyara::message::valid () const inline
Definition at line 221 of file xqueue.h.
References address, and dhyara::peer_address::is_null().
Member Data Documentation
address
dhyara::peer_address dhyara::message::address
Definition at line 225 of file xqueue.h.
Referenced by clear(), dhyara::network_fifo< dhyara::queue_size >::dequeue(), dhyara::network_fifo< dhyara::queue_size >::loop(), dhyara::network_fifo< dhyara::queue_size >::peek(), and valid().
frame
dhyara::frame dhyara::message::frame
Definition at line 226 of file xqueue.h.
Referenced by dhyara::network_fifo< dhyara::queue_size >::dequeue(), dhyara::network_fifo< dhyara::queue_size >::loop(), and dhyara::network_fifo< dhyara::queue_size >::peek().
The documentation for this struct was generated from the following file:
includes/dhyara/xqueue.h