Dhyara: dhyara::link Struct Reference
dhyara::link Struct Reference
Communication
Link Layer Medium is responsible for sending packets and processing the received packets.
#include <link.h>
Classes
struct proxy
Public Types
typedef std::function< void(const dhyara::peer_address &, const dhyara::frame &)> callback_type
typedef std::map< dhyara::packets::type, callback_type > handlers_map_type
typedef std::map< dhyara::packets::type, std::pair< std::size_t, std::size_t > > counters_map_type
typedef dhyara::network_fifo< dhyara::queue_size > fifo_type
typedef dhyara::xqueue< dhyara::message, dhyara::queue_size > xqueue_type
Public Member Functions
link ()
Construct.
void init ()
Initialize the medium.
template<typename PacketT >
bool send_local (const dhyara::peer_address &addr, packets::type type, const PacketT &packet)
Sends a packet to an immediate neighbour directly in one hop.
template<typename PacketT >
bool send (const dhyara::peer_address &addr, packets::type type, const PacketT &packet)
Sends a packet via the best intermediate node.
void _esp_sent_cb (const uint8_t *target, esp_now_send_status_t status)
ESP Send Callback.
void _esp_rcvd_cb (const uint8_t *source, const uint8_t *data, int len)
Process raw data received.
void _esp_promiscous_rx_cb (void *buffer, wifi_promiscuous_pkt_type_t type)
Updates RSSI by using the frame headers received in the promiscous mode.
void install (dhyara::packets::type type, callback_type cb)
Associate an action with a packet type.
proxy operator[] (dhyara::packets::type type)
Conveniance function to install an action (associate an action with a packet type).
void start_rcv (std::size_t ticks=0xffffffffUL)
start receive loop never returns
dhyara::neighbourhood & neighbours ()
immediate neighbourhood
dhyara::routing & routes ()
routing table
const dhyara::peer::address & address () const
local address
void reset (dhyara::packets::type type)
reset counter
std::size_t tx (dhyara::packets::type type) const
number of packets received for the given type
std::size_t rx (dhyara::packets::type type) const
number of packets recieved for the given type
std::int8_t max_rssi () const
Maximum rssi in the neighbourhood.
dhyara::delay_type lost () const
Duration for which the node has not heard anything from its neighbourhood (in us).
esp_err_t connect (const dhyara::peer_address &target)
Associate with the target AP using the station interface.
Detailed Description
Link Layer Medium is responsible for sending packets and processing the received packets.
All received data should be forwarded to the link via _esp_sent_cb which wil then be processed through the installed actions.
dhyara::link medium; // A communication medium
dhyara::actions::acknowledgement acknowledgement(medium.local()); // Handler for acknowledgement packets
medium[dhyara::packets::type::acknowledgement] = acknowledgement;
// associate other actions ...
medium.start();
Definition at line 38 of file link.h.
Member Typedef Documentation
callback_type
typedef std::function<void (const dhyara::peer_address&, const dhyara::frame&)> dhyara::link::callback_type
Definition at line 39 of file link.h.
counters_map_type
typedef std::map<dhyara::packets::type, std::pair<std::size_t, std::size_t> > dhyara::link::counters_map_type
Definition at line 41 of file link.h.
fifo_type
typedef dhyara::network_fifo<dhyara::queue_size> dhyara::link::fifo_type
Definition at line 42 of file link.h.
handlers_map_type
typedef std::map<dhyara::packets::type, callback_type> dhyara::link::handlers_map_type
Definition at line 40 of file link.h.
xqueue_type
typedef dhyara::xqueue<dhyara::message, dhyara::queue_size> dhyara::link::xqueue_type
Definition at line 43 of file link.h.
Constructor & Destructor Documentation
link()
dhyara::link::link ()
Construct.
Member Function Documentation
_esp_promiscous_rx_cb()
void dhyara::link::_esp_promiscous_rx_cb (void * buffer, wifi_promiscuous_pkt_type_t type)
Updates RSSI by using the frame headers received in the promiscous mode.
Warning
Only the ESP Wifi promiscous rx callback should call this function
Parameters
buffer received data
type promiscous packet type
_esp_rcvd_cb()
void dhyara::link::_esp_rcvd_cb (const uint8_t * source, const uint8_t * data, int len)
Process raw data received.
Create a frame from the received data and passes that to queue for further procesing. Leaves wifi stack
Warning
Only the ESP NOW receive callback should call this function
Parameters
source source address
data raw data received
len length of the raw data
_esp_sent_cb()
void dhyara::link::_esp_sent_cb (const uint8_t * target, esp_now_send_status_t status)
ESP Send Callback.
Warning
Only the ESP NOW sent callback should call this function
Parameters
target target address
status status
address()
const dhyara::peer::address& dhyara::link::address () const inline
local address
Definition at line 172 of file link.h.
connect()
esp_err_t dhyara::link::connect (const dhyara::peer_address & target)
Associate with the target AP using the station interface.
init()
void dhyara::link::init ()
Initialize the medium.
install()
void dhyara::link::install (dhyara::packets::type type, callback_type cb)
Associate an action with a packet type.
The operator()() overload of that action will be called with the received packet.
Parameters
type packet type
cb The action
Referenced by dhyara::link::proxy::operator=().
lost()
dhyara::delay_type dhyara::link::lost () const
Duration for which the node has not heard anything from its neighbourhood (in us).
max_rssi()
std::int8_t dhyara::link::max_rssi () const
Maximum rssi in the neighbourhood.
neighbours()
dhyara::neighbourhood& dhyara::link::neighbours () inline
immediate neighbourhood
Definition at line 163 of file link.h.
operator[]()
proxy dhyara::link::operator[] (dhyara::packets::type type) inline
Conveniance function to install an action (associate an action with a packet type).
dhyara::link medium;
dhyara::actions::beacon beacon(medium);
medium[dhyara::packets::type::beacon] = beacon;
Parameters
type packet type
Definition at line 144 of file link.h.
reset()
void dhyara::link::reset (dhyara::packets::type type)
reset counter
routes()
dhyara::routing& dhyara::link::routes () inline
routing table
Definition at line 167 of file link.h.
rx()
std::size_t dhyara::link::rx (dhyara::packets::type type) const
number of packets recieved for the given type
Parameters
type packet type
send()
template<typename PacketT > bool dhyara::link::send (const dhyara::peer_address & addr, packets::type type, const PacketT & packet) inline
Sends a packet via the best intermediate node.
If the destination address is immediate neighbour then sends directly.
Parameters
addr target peer address
type packet type
packet packet object
Definition at line 91 of file link.h.
References dhyara::peer_address::is_null(), dhyara::routing::next(), send_local(), and dhyara::routing::next_hop::via().
send_local()
template<typename PacketT > bool dhyara::link::send_local (const dhyara::peer_address & addr, packets::type type, const PacketT & packet) inline
Sends a packet to an immediate neighbour directly in one hop.
Parameters
addr target peer address
type packet type
packet packet object
Definition at line 75 of file link.h.
References dhyara::frame::_buffer, dhyara::utils::printer::out(), and dhyara::write().
Referenced by send().
start_rcv()
void dhyara::link::start_rcv (std::size_t ticks = 0xffffffffUL)
start receive loop never returns
tx()
std::size_t dhyara::link::tx (dhyara::packets::type type) const
number of packets received for the given type
Parameters
type packet type
The documentation for this struct was generated from the following file:
includes/dhyara/link.h