Dhyara: dhyara::packets::chunk Struct Reference
dhyara::packets::chunk Struct Reference
Packets
Chunk of a variable sized data.
#include <chunk.h>
Public Types
enum { capacity = 250 - (sizeof(chunk_header) +2) }
typedef std::array< std::uint8_t, 6 > raw_address_type
typedef std::array< std::uint8_t, capacity > buffer_type
typedef buffer_type::const_iterator const_iterator_type
Public Member Functions
chunk ()
Construct an empty chunk.
template<typename InputIt >
chunk (const dhyara::peer::address &target, const dhyara::peer::address &source, InputIt begin, std::uint8_t length, std::uint8_t packet, std::uint8_t pending=0)
Construct a chunk by reading length bytes from begin iterator.
const chunk_header & header () const
returns the header
std::size_t size () const
byte size of the chunk
template<typename OutIt >
OutIt copy (OutIt it)
copy the contents of the chunk to the output iterator provided
const_iterator_type begin () const
begin of the chunk payload
const_iterator_type end () const
end of teh chunk payload
std::uint8_t length () const
length of the chunk
dhyara::peer::address target () const
target of the chunk
dhyara::peer::address source () const
source of the chunk
std::uint8_t packet () const
packet id of the chunk
std::uint8_t pending () const
number of chunks pending after this
bool is_last () const
checks whether the chunks is the last
Public Attributes
chunk_header _header
buffer_type _buffer
Detailed Description
Chunk of a variable sized data.
Definition at line 84 of file chunk.h.
Member Typedef Documentation
buffer_type
typedef std::array<std::uint8_t, capacity> dhyara::packets::chunk::buffer_type
Definition at line 88 of file chunk.h.
const_iterator_type
typedef buffer_type::const_iterator dhyara::packets::chunk::const_iterator_type
Definition at line 89 of file chunk.h.
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::chunk::raw_address_type
Definition at line 85 of file chunk.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
capacity
Definition at line 87 of file chunk.h.
Constructor & Destructor Documentation
chunk() [1/2]
dhyara::packets::chunk::chunk () inline
Construct an empty chunk.
Definition at line 97 of file chunk.h.
References _buffer.
Referenced by size().
chunk() [2/2]
template<typename InputIt > dhyara::packets::chunk::chunk (const dhyara::peer::address & target, const dhyara::peer::address & source, InputIt begin, std::uint8_t length, std::uint8_t packet, std::uint8_t pending = 0) inline
Construct a chunk by reading length bytes from begin iterator.
Parameters
target the target MAC address
source the source MAC address
begin the begin iterator
length length of the chunk
packet packet id of the data packet of which this chunk is part of
pending number of chunks pending after this
Definition at line 111 of file chunk.h.
References _buffer, _header, begin(), end(), and dhyara::packets::chunk_header::length().
Member Function Documentation
begin()
const_iterator_type dhyara::packets::chunk::begin () const inline
begin of the chunk payload
Definition at line 136 of file chunk.h.
References _buffer.
Referenced by chunk(), and end().
copy()
template<typename OutIt > OutIt dhyara::packets::chunk::copy (OutIt it) inline
copy the contents of the chunk to the output iterator provided
Parameters
it output iterator
Definition at line 128 of file chunk.h.
References _buffer, _header, and dhyara::packets::chunk_header::length().
end()
const_iterator_type dhyara::packets::chunk::end () const inline
end of teh chunk payload
Definition at line 140 of file chunk.h.
References _header, begin(), and dhyara::packets::chunk_header::length().
Referenced by chunk().
header()
const chunk_header& dhyara::packets::chunk::header () const inline
returns the header
Definition at line 118 of file chunk.h.
References _header.
is_last()
bool dhyara::packets::chunk::is_last () const inline
checks whether the chunks is the last
Definition at line 165 of file chunk.h.
References pending().
length()
std::uint8_t dhyara::packets::chunk::length () const inline
length of the chunk
Definition at line 145 of file chunk.h.
References _header, and dhyara::packets::chunk_header::_length.
packet()
std::uint8_t dhyara::packets::chunk::packet () const inline
packet id of the chunk
Definition at line 157 of file chunk.h.
References _header, and dhyara::packets::chunk_header::packet().
pending()
std::uint8_t dhyara::packets::chunk::pending () const inline
number of chunks pending after this
Definition at line 161 of file chunk.h.
References _header, and dhyara::packets::chunk_header::pending().
Referenced by is_last().
size()
std::size_t dhyara::packets::chunk::size () const inline
byte size of the chunk
Definition at line 122 of file chunk.h.
References chunk().
source()
dhyara::peer::address dhyara::packets::chunk::source () const inline
source of the chunk
Definition at line 153 of file chunk.h.
References _header, and dhyara::packets::chunk_header::source().
target()
dhyara::peer::address dhyara::packets::chunk::target () const inline
target of the chunk
Definition at line 149 of file chunk.h.
References _header, and dhyara::packets::chunk_header::target().
Member Data Documentation
_buffer
buffer_type dhyara::packets::chunk::_buffer
Definition at line 92 of file chunk.h.
Referenced by begin(), chunk(), and copy().
_header
chunk_header dhyara::packets::chunk::_header
Definition at line 91 of file chunk.h.
Referenced by chunk(), copy(), end(), header(), length(), packet(), pending(), source(), and target().
The documentation for this struct was generated from the following file:
includes/dhyara/packets/chunk.h