Dhyara: dhyara::peer_address Struct Reference
dhyara::peer_address Struct Reference
Interface
peer address (mac address)
#include <peer.h>
Public Types
typedef std::array< std::uint8_t, 6 > container_type
Public Member Functions
peer_address (const container_type &addr)
construct mac address by an array
peer_address (std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6)
construct mac address by octets
peer_address (const std::uint8_t *bytes)
construct mac address by providing address to an array
peer_address (const std::string &addr)
construct mac address by string
std::string to_string () const
convert to string
const std::uint8_t * raw () const
raw array
std::uint8_t b1 () const
first octet of the mac address
std::uint8_t b2 () const
second octet of the mac address
std::uint8_t b3 () const
third octet of the mac address
std::uint8_t b4 () const
fourth octet of the mac address
std::uint8_t b5 () const
fifth octet of the mac address
std::uint8_t b6 () const
sixth octed of the mac address
std::uint64_t hash () const
64 bit hash value for the mac address
bool operator< (const peer_address &other) const
Less than comparator.
bool operator== (const peer_address &other) const
Comparator.
bool operator== (const std::string &addr) const
Compare with string.
bool operator!= (const peer_address &other) const
Comparator.
bool operator!= (const std::string &addr) const
Comparator.
void set (const std::uint8_t *bytes)
Set the octets directly.
bool is_null () const
check whether the mac address is null
bool is_broadcast () const
check whether the mac address is broadcast
Static Public Member Functions
static peer_address null ()
null mac
static peer_address all ()
broadcast mac
Detailed Description
peer address (mac address)
Definition at line 29 of file peer.h.
Member Typedef Documentation
container_type
typedef std::array<std::uint8_t, 6> dhyara::peer_address::container_type
Definition at line 30 of file peer.h.
Constructor & Destructor Documentation
peer_address() [1/4]
dhyara::peer_address::peer_address (const container_type & addr) explicit
construct mac address by an array
Referenced by all(), and null().
peer_address() [2/4]
dhyara::peer_address::peer_address (std::uint8_t b1, std::uint8_t b2, std::uint8_t b3, std::uint8_t b4, std::uint8_t b5, std::uint8_t b6)
construct mac address by octets
peer_address() [3/4]
dhyara::peer_address::peer_address (const std::uint8_t * bytes) explicit
construct mac address by providing address to an array
peer_address() [4/4]
dhyara::peer_address::peer_address (const std::string & addr) explicit
construct mac address by string
Member Function Documentation
all()
static peer_address dhyara::peer_address::all () inline static
broadcast mac
Definition at line 56 of file peer.h.
References peer_address().
b1()
std::uint8_t dhyara::peer_address::b1 () const inline
first octet of the mac address
Definition at line 69 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
b2()
std::uint8_t dhyara::peer_address::b2 () const inline
second octet of the mac address
Definition at line 73 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
b3()
std::uint8_t dhyara::peer_address::b3 () const inline
third octet of the mac address
Definition at line 77 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
b4()
std::uint8_t dhyara::peer_address::b4 () const inline
fourth octet of the mac address
Definition at line 81 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
b5()
std::uint8_t dhyara::peer_address::b5 () const inline
fifth octet of the mac address
Definition at line 85 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
b6()
std::uint8_t dhyara::peer_address::b6 () const inline
sixth octed of the mac address
Definition at line 89 of file peer.h.
Referenced by dhyara::packets::advertisement::advertisement(), dhyara::packets::delivered::delivered(), dhyara::packets::echo_lost::echo_lost(), size(), and target().
hash()
std::uint64_t dhyara::peer_address::hash () const
64 bit hash value for the mac address
Referenced by std::hash< dhyara::peer_address >::operator()(), and std::hash< dhyara::peer >::operator()().
is_broadcast()
bool dhyara::peer_address::is_broadcast () const inline
check whether the mac address is broadcast
Definition at line 127 of file peer.h.
is_null()
bool dhyara::peer_address::is_null () const inline
check whether the mac address is null
Definition at line 123 of file peer.h.
Referenced by dhyara::link::send(), and dhyara::message::valid().
null()
static peer_address dhyara::peer_address::null () inline static
null mac
Definition at line 52 of file peer.h.
References peer_address().
Referenced by dhyara::message::clear().
operator!=() [1/2]
bool dhyara::peer_address::operator!= (const peer_address & other) const inline
Comparator.
Definition at line 109 of file peer.h.
operator!=() [2/2]
bool dhyara::peer_address::operator!= (const std::string & addr) const inline
Comparator.
Definition at line 113 of file peer.h.
operator<()
bool dhyara::peer_address::operator< (const peer_address & other) const
Less than comparator.
operator==() [1/2]
bool dhyara::peer_address::operator== (const peer_address & other) const
Comparator.
operator==() [2/2]
bool dhyara::peer_address::operator== (const std::string & addr) const
Compare with string.
raw()
const std::uint8_t* dhyara::peer_address::raw () const inline
raw array
Definition at line 65 of file peer.h.
set()
void dhyara::peer_address::set (const std::uint8_t * bytes)
Set the octets directly.
to_string()
std::string dhyara::peer_address::to_string () const
convert to string
The documentation for this struct was generated from the following file:
/home/runner/work/dhyara/dhyara/includes/dhyara/peer.h