Dhyara: dhyara::packets::advertisement Struct Reference
dhyara::packets::advertisement Struct Reference
Packets
advertisement packet sent after an acknowledgement packet is received.
#include <advertisement.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
advertisement ()
Construct an advertisement packet with null destination and no delay.
advertisement (const dhyara::peer::address &dest, delay_type delay)
Construct an advertisement packet with the given destination and the delay specified.
std::size_t size () const
Size of the packet.
dhyara::peer::address dest () const
Destination in the advertisement packet.
delay_type delay () const
Delay in teh advertisement packet.
Public Attributes
raw_address_type _dest
delay_type _delay
Detailed Description
advertisement packet sent after an acknowledgement packet is received.
The advertisement packet contains route information about a neighbour. The route information includes one trip delay.
Definition at line 27 of file advertisement.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::advertisement::raw_address_type
Definition at line 28 of file advertisement.h.
Constructor & Destructor Documentation
advertisement() [1/2]
dhyara::packets::advertisement::advertisement () inline
Construct an advertisement packet with null destination and no delay.
Definition at line 36 of file advertisement.h.
Referenced by size().
advertisement() [2/2]
dhyara::packets::advertisement::advertisement (const dhyara::peer::address & dest, delay_type delay) inline
Construct an advertisement packet with the given destination and the delay specified.
Parameters
dest The destination address
delay The delay encountered in the route
Definition at line 43 of file advertisement.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and dest().
Member Function Documentation
delay()
delay_type dhyara::packets::advertisement::delay () const inline
Delay in teh advertisement packet.
Definition at line 57 of file advertisement.h.
References _delay.
dest()
dhyara::peer::address dhyara::packets::advertisement::dest () const inline
Destination in the advertisement packet.
Definition at line 53 of file advertisement.h.
References _dest.
Referenced by advertisement().
size()
std::size_t dhyara::packets::advertisement::size () const inline
Size of the packet.
Definition at line 49 of file advertisement.h.
References advertisement().
Member Data Documentation
_delay
delay_type dhyara::packets::advertisement::_delay
Definition at line 31 of file advertisement.h.
Referenced by delay().
_dest
raw_address_type dhyara::packets::advertisement::_dest
Definition at line 30 of file advertisement.h.
Referenced by dest().
The documentation for this struct was generated from the following file:
dhyara/packets/advertisement.h