Dhyara: dhyara::frame Struct Reference
dhyara::frame Struct Reference
Packets
A 250 bytes frame is defined by a 2 bytes header and 248 bytes payload.
#include <frame.h>
Public Member Functions
frame ()
Construct a frame that is supposed to contain a packet of unknown type.
frame (packets::type type)
Construct a frame that is supposed to contain a packet of the given type.
void copy_from (const dhyara::packets::data &data, std::uint8_t n)
Construct a chunk frame directly from data.
frame (packets::type type, std::size_t len)
Construct a frame of provided payload payload that is supposed to contain a packet of the given type.
bool valid () const
CHecks whether the frame is valid or not.
packets::type type () const
Packet type in the frame.
void type (packets::type t)
Packet type in the frame.
std::size_t length () const
Length of the frame.
void length (std::size_t l)
Length of the frame.
std::size_t size () const
Size of the frame.
void clear ()
Clears the frame, zerofills the internal buffer.
Static Public Member Functions
static constexpr std::uint8_t header_size ()
Size of the header of the frame (2 bytes)
template<typename PacketT >
static frame create (packets::type type, const PacketT &packet)
Create a frame from a packet and a packet type.
template<typename PacketT >
static frame * create_new (packets::type type, const PacketT &packet)
Creates a frame on heap with teh given packet and a packet type.
Detailed Description
A 250 bytes frame is defined by a 2 bytes header and 248 bytes payload.
The 2 bytes header insludes one byte for packet type and another byte for the length of the payload.
Definition at line 26 of file frame.h.
Constructor & Destructor Documentation
frame() [1/2]
dhyara::frame::frame (packets::type type) inline
Construct a frame that is supposed to contain a packet of the given type.
Parameters
type type of the packet
Definition at line 43 of file frame.h.
frame() [2/2]
dhyara::frame::frame (packets::type type, std::size_t len) inline
Construct a frame of provided payload payload that is supposed to contain a packet of the given type.
Parameters
type packet type
len length of the frame
Definition at line 64 of file frame.h.
Member Function Documentation
create()
template<typename PacketT > static frame dhyara::frame::create (packets::type type, const PacketT & packet) inline static
Create a frame from a packet and a packet type.
Parameters
type packet type
packet packet to put inside the frame
Returns
returns the created frame
Definition at line 117 of file frame.h.
References type(), and dhyara::write().
create_new()
template<typename PacketT > static frame* dhyara::frame::create_new (packets::type type, const PacketT & packet) inline static
Creates a frame on heap with teh given packet and a packet type.
Parameters
type packet type
packet packet to put inside the frame
Returns
returns pointer to the newly created frame
Definition at line 129 of file frame.h.
References frame(), type(), and dhyara::write().
The documentation for this struct was generated from the following file:
includes/dhyara/frame.h