Dhyara: dhyara::watcher< WatchedT > Struct Template Reference
dhyara::watcher< WatchedT > Struct Template Reference
watcher
#include <xqueue.h>
Public Types
typedef xqueue< WatchedT, 1 > xqueue_type
Public Member Functions
bool notify (const WatchedT &watched)
notify the watcher
bool watch (WatchedT &watched)
bool sleeping ()
Public Attributes
xqueue_type _notification
Detailed Description
template<typename WatchedT>
struct dhyara::watcher< WatchedT >
watcher
Definition at line 159 of file xqueue.h.
Member Typedef Documentation
xqueue_type
template<typename WatchedT > typedef xqueue<WatchedT, 1> dhyara::watcher< WatchedT >::xqueue_type
Definition at line 160 of file xqueue.h.
Member Function Documentation
notify()
template<typename WatchedT > bool dhyara::watcher< WatchedT >::notify (const WatchedT & watched) inline
notify the watcher
Definition at line 167 of file xqueue.h.
Referenced by dhyara::notifier::notify(), and dhyara::mutex::unlock().
sleeping()
template<typename WatchedT > bool dhyara::watcher< WatchedT >::sleeping () inline
Definition at line 173 of file xqueue.h.
watch()
template<typename WatchedT > bool dhyara::watcher< WatchedT >::watch (WatchedT & watched) inline
Definition at line 170 of file xqueue.h.
Referenced by dhyara::mutex::lock(), and dhyara::notifier::watch().
Member Data Documentation
_notification
template<typename WatchedT > xqueue_type dhyara::watcher< WatchedT >::_notification
Definition at line 162 of file xqueue.h.
Referenced by dhyara::watcher< char >::notify(), dhyara::watcher< char >::sleeping(), and dhyara::watcher< char >::watch().
The documentation for this struct was generated from the following file:
dhyara/xqueue.h