Dhyara: dhyara::routing Struct Reference
dhyara::routing Struct Reference
Routing
routing table
#include <routing.h>
Classes
struct next_hop
The best next hop for the given target.
struct route
A route to a destination via a node (A null via should be considered as one hop)
struct route_metric
metric of a route
Public Types
typedef std::map< route, route_metric > table_type
typedef std::map< dhyara::peer::address, next_hop > next_vector_type
Public Member Functions
routing (delay_type def=std::numeric_limits< delay_type >::max())
Construct.
bool exists (const dhyara::peer::address &dst) const
checks whether there exists any route for the given destination
bool exists (const route &r) const
checks whether an rtt is associated with the given route
bool update (const route &r, const delay_type &d)
updates routing table with rtt of a route.
bool depreciate (const route &r)
depritiate a route
dhyara::routing::next_hop next (const dhyara::peer::address &dst) const
next node to for the final destination dst
void depreciate ()
depreciate a route that was not updated within dhyara::route_expiry time
void depreciate (std::function< void(const dhyara::routing::route &, delay_type)> notify)
depreciate a route that was not updated within dhyara::route_expiry time
std::ostream & print (std::ostream &os) const
print the routing table and current next hop vector
table_type::const_iterator route_begin () const
begin of the routing table
table_type::const_iterator route_end () const
end of the routing table
next_vector_type::const_iterator next_begin () const
begin of the next best vector
next_vector_type::const_iterator next_end () const
end of the next best vector
dhyara::delay_type lost_since () const
Last time the routing table was updated.
Detailed Description
routing table
Definition at line 28 of file routing.h.
Member Typedef Documentation
next_vector_type
typedef std::map<dhyara::peer::address, next_hop> dhyara::routing::next_vector_type
Definition at line 148 of file routing.h.
table_type
typedef std::map<route, route_metric> dhyara::routing::table_type
Definition at line 112 of file routing.h.
Constructor & Destructor Documentation
routing()
dhyara::routing::routing (delay_type def = std::numeric_limits<delay_type>::max()) inline explicit
Construct.
Definition at line 153 of file routing.h.
Member Function Documentation
depreciate() [1/3]
void dhyara::routing::depreciate ()
depreciate a route that was not updated within dhyara::route_expiry time
Referenced by depreciate().
depreciate() [2/3]
bool dhyara::routing::depreciate (const route & r)
depritiate a route
depreciate() [3/3]
void dhyara::routing::depreciate (std::function< void(const dhyara::routing::route &, delay_type)> notify) inline
depreciate a route that was not updated within dhyara::route_expiry time
Definition at line 186 of file routing.h.
References depreciate(), and dhyara::route_expiry.
exists() [1/2]
bool dhyara::routing::exists (const dhyara::peer::address & dst) const
checks whether there exists any route for the given destination
Parameters
dst the final destination
exists() [2/2]
bool dhyara::routing::exists (const route & r) const
checks whether an rtt is associated with the given route
Parameters
r the route (combination of destination and next hop)
lost_since()
dhyara::delay_type dhyara::routing::lost_since () const
Last time the routing table was updated.
next()
dhyara::routing::next_hop dhyara::routing::next (const dhyara::peer::address & dst) const
next node to for the final destination dst
Referenced by dhyara::link::send().
next_begin()
next_vector_type::const_iterator dhyara::routing::next_begin () const inline
begin of the next best vector
Definition at line 219 of file routing.h.
next_end()
next_vector_type::const_iterator dhyara::routing::next_end () const inline
end of the next best vector
Definition at line 223 of file routing.h.
print()
std::ostream& dhyara::routing::print (std::ostream & os) const
print the routing table and current next hop vector
route_begin()
table_type::const_iterator dhyara::routing::route_begin () const inline
begin of the routing table
Definition at line 211 of file routing.h.
route_end()
table_type::const_iterator dhyara::routing::route_end () const inline
end of the routing table
Definition at line 215 of file routing.h.
update()
bool dhyara::routing::update (const route & r, const delay_type & d)
updates routing table with rtt of a route.
returning true signifies that min values for the destination has been altered due to this route. returnign false signifies that the min values are still the same
The documentation for this struct was generated from the following file:
includes/dhyara/routing.h