Dhyara: dhyara::packets::chunk_header Struct Reference
dhyara::packets::chunk_header Struct Reference
Packets
Header in the chunk.
#include <chunk.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
chunk_header ()
Construct a chunk header with null target and source.
chunk_header (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending=0)
Construct a chunk header with provided parameters.
std::uint8_t length () const
length of the chunk
std::size_t size () const
byte size of the header
dhyara::peer::address target () const
target MAC address of the chunk
dhyara::peer::address source () const
source MAC address of the chunk
std::uint8_t packet () const
packet id of the data packet that this chunk is part of
std::uint8_t pending () const
number of pending chunks after this
bool is_last () const
Whether this is the last chunk.
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint8_t _length
std::uint8_t _packet
std::uint8_t _pending
Detailed Description
Header in the chunk.
Definition at line 24 of file chunk.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::chunk_header::raw_address_type
Definition at line 25 of file chunk.h.
Constructor & Destructor Documentation
chunk_header() [1/2]
dhyara::packets::chunk_header::chunk_header () inline
Construct a chunk header with null target and source.
length, packet id, pending is set to 0
Definition at line 36 of file chunk.h.
Referenced by size().
chunk_header() [2/2]
dhyara::packets::chunk_header::chunk_header (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint8_t length, std::uint8_t packet, std::uint8_t pending = 0) inline
Construct a chunk header with provided parameters.
Parameters
target target MAC address
source source MAC address
length length of the chunk
packet packet id of the data packet
pending number of chunks pending after this
Definition at line 45 of file chunk.h.
References dhyara::peer_address::b1(), dhyara::peer_address::b2(), dhyara::peer_address::b3(), dhyara::peer_address::b4(), dhyara::peer_address::b5(), dhyara::peer_address::b6(), and target().
Member Function Documentation
is_last()
bool dhyara::packets::chunk_header::is_last () const inline
Whether this is the last chunk.
Definition at line 77 of file chunk.h.
References pending().
length()
std::uint8_t dhyara::packets::chunk_header::length () const inline
length of the chunk
Definition at line 53 of file chunk.h.
References _length.
Referenced by dhyara::packets::chunk::chunk(), dhyara::packets::chunk::copy(), and dhyara::packets::chunk::end().
packet()
std::uint8_t dhyara::packets::chunk_header::packet () const inline
packet id of the data packet that this chunk is part of
Definition at line 69 of file chunk.h.
References _packet.
Referenced by dhyara::packets::chunk::packet().
pending()
std::uint8_t dhyara::packets::chunk_header::pending () const inline
number of pending chunks after this
Definition at line 73 of file chunk.h.
References _pending.
Referenced by is_last(), and dhyara::packets::chunk::pending().
size()
std::size_t dhyara::packets::chunk_header::size () const inline
byte size of the header
Definition at line 57 of file chunk.h.
References chunk_header().
source()
dhyara::peer::address dhyara::packets::chunk_header::source () const inline
source MAC address of the chunk
Definition at line 65 of file chunk.h.
References _source.
Referenced by dhyara::packets::chunk::source().
target()
dhyara::peer::address dhyara::packets::chunk_header::target () const inline
target MAC address of the chunk
Definition at line 61 of file chunk.h.
References _target.
Referenced by chunk_header(), and dhyara::packets::chunk::target().
Member Data Documentation
_length
std::uint8_t dhyara::packets::chunk_header::_length
Definition at line 29 of file chunk.h.
Referenced by length(), and dhyara::packets::chunk::length().
_packet
std::uint8_t dhyara::packets::chunk_header::_packet
Definition at line 30 of file chunk.h.
Referenced by packet().
_pending
std::uint8_t dhyara::packets::chunk_header::_pending
Definition at line 31 of file chunk.h.
Referenced by pending().
_source
raw_address_type dhyara::packets::chunk_header::_source
Definition at line 28 of file chunk.h.
Referenced by source().
_target
raw_address_type dhyara::packets::chunk_header::_target
Definition at line 27 of file chunk.h.
Referenced by target().
The documentation for this struct was generated from the following file:
includes/dhyara/packets/chunk.h