Dhyara: dhyara::network Struct Reference
dhyara::network Struct Reference
Interface
The dhyara ad-hoc network.
#include <network.h>
Public Member Functions
network ()=delete
Not default constructible.
network (const network &)=delete
Not copyable.
network & operator= (const network &)=delete
Not Copyable.
network (dhyara::link &link)
Construct a network with a reference to the link.
void start ()
main network I/O
template<typename InputIt >
bool send (const dhyara::peer_address &target, InputIt begin, InputIt end)
Send a variable sized data to the destination.
bool send (const dhyara::peer_address &target, const dhyara::packets::data &data)
Send a data packet.
void on_data (dhyara::actions::chunk::data_callback_type slot)
set a callback which will be called once a complete data is received
dhyara::link & link ()
Link.
dhyara::synchronizer & synchronizer ()
synchronizer
dhyara::actions::beacon & beacon ()
beacon action
dhyara::actions::acknowledgement & acknowledgement ()
acknowledgement action
dhyara::actions::advertisement & advertisement ()
advertisement action
dhyara::actions::echo_request & echo_request ()
echo_request action
dhyara::actions::echo_reply & echo_reply ()
echo_reply action
dhyara::actions::echo_lost & echo_lost ()
echo_lost action
dhyara::actions::chunk & chunk ()
chunk action
dhyara::actions::delivered & delivered ()
delivered action
Detailed Description
The dhyara ad-hoc network.
The network is started using the start method. All related networking tasks and actions are created and maintained by the network.
Definition at line 27 of file network.h.
Constructor & Destructor Documentation
network() [1/3]
dhyara::network::network () delete
Not default constructible.
network() [2/3]
dhyara::network::network (const network &) delete
Not copyable.
network() [3/3]
dhyara::network::network (dhyara::link & link)
Construct a network with a reference to the link.
Member Function Documentation
acknowledgement()
dhyara::actions::acknowledgement& dhyara::network::acknowledgement () inline
acknowledgement action
Definition at line 102 of file network.h.
advertisement()
dhyara::actions::advertisement& dhyara::network::advertisement () inline
advertisement action
Definition at line 106 of file network.h.
beacon()
dhyara::actions::beacon& dhyara::network::beacon () inline
beacon action
Definition at line 98 of file network.h.
chunk()
dhyara::actions::chunk& dhyara::network::chunk () inline
chunk action
Definition at line 122 of file network.h.
delivered()
dhyara::actions::delivered& dhyara::network::delivered () inline
delivered action
Definition at line 126 of file network.h.
echo_lost()
dhyara::actions::echo_lost& dhyara::network::echo_lost () inline
echo_lost action
Definition at line 118 of file network.h.
echo_reply()
dhyara::actions::echo_reply& dhyara::network::echo_reply () inline
echo_reply action
Definition at line 114 of file network.h.
echo_request()
dhyara::actions::echo_request& dhyara::network::echo_request () inline
echo_request action
Definition at line 110 of file network.h.
link()
dhyara::link& dhyara::network::link () inline
Link.
Definition at line 90 of file network.h.
on_data()
void dhyara::network::on_data (dhyara::actions::chunk::data_callback_type slot)
set a callback which will be called once a complete data is received
operator=()
network& dhyara::network::operator= (const network &) delete
Not Copyable.
send() [1/2]
bool dhyara::network::send (const dhyara::peer_address & target, const dhyara::packets::data & data)
Send a data packet.
See also
dhyara::packets::data
send() [2/2]
template<typename InputIt > bool dhyara::network::send (const dhyara::peer_address & target, InputIt begin, InputIt end) inline
Send a variable sized data to the destination.
The data may be splitted into multiple chunks if its not accomodable in a single packet. Any forward iterable sequence, that can be dereferenced as a byte can be considered ad data.
Parameters
target target mac address
begin begin iterator to the data that has to be sent
end end iterator to the data that that has to be sent
Definition at line 59 of file network.h.
References begin(), end(), and target().
start()
void dhyara::network::start ()
main network I/O
synchronizer()
dhyara::synchronizer& dhyara::network::synchronizer () inline
synchronizer
Definition at line 94 of file network.h.
The documentation for this struct was generated from the following file:
/home/runner/work/dhyara/dhyara/includes/dhyara/network.h