Dhyara: dhyara::packets::echo_request Struct Reference
dhyara::packets::echo_request Struct Reference
Packets
An echo request.
#include <echo_request.h>
Public Types
typedef std::array< std::uint8_t, 6 > raw_address_type
Public Member Functions
echo_request ()
Construct an echo request to null destination originating from null destination on current time with default ttl value.
echo_request (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint32_t seq=0, std::uint64_t time=0, std::uint8_t ttl=255)
Construct an echo request to the target originating from the source with the provided sequence number, time and ttl.
std::size_t size () const
Size of the packet.
std::uint64_t time () const
Time in the packet.
std::uint32_t seq () const
Sequence number of the ICMP packet.
std::uint8_t ttl () const
TTL of the ICMP request.
dhyara::peer::address target () const
Target address of the ICMP packet.
dhyara::peer::address source () const
Source address of the ICMP packet.
Public Attributes
raw_address_type _target
raw_address_type _source
std::uint32_t _seq
std::uint64_t _time
std::uint8_t _ttl
Detailed Description
An echo request.
Definition at line 25 of file echo_request.h.
Member Typedef Documentation
raw_address_type
typedef std::array<std::uint8_t, 6> dhyara::packets::echo_request::raw_address_type
Definition at line 26 of file echo_request.h.
Constructor & Destructor Documentation
echo_request() [1/2]
dhyara::packets::echo_request::echo_request () inline
Construct an echo request to null destination originating from null destination on current time with default ttl value.
Definition at line 37 of file echo_request.h.
Referenced by size().
echo_request() [2/2]
dhyara::packets::echo_request::echo_request (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint32_t seq = 0, std::uint64_t time = 0, std::uint8_t ttl = 255) inline
Construct an echo request to the target originating from the source with the provided sequence number, time and ttl.
Parameters
target the target mac address
source the originating mac address
seq the sequence number of this ICMP request
time the time in the ICMP request (defaults to current time)
ttl TTL value in the ICMP request
Definition at line 50 of file echo_request.h.
Member Function Documentation
seq()
std::uint32_t dhyara::packets::echo_request::seq () const inline
Sequence number of the ICMP packet.
Definition at line 66 of file echo_request.h.
References _seq.
size()
std::size_t dhyara::packets::echo_request::size () const inline
Size of the packet.
Definition at line 58 of file echo_request.h.
References echo_request().
source()
dhyara::peer::address dhyara::packets::echo_request::source () const inline
Source address of the ICMP packet.
Definition at line 78 of file echo_request.h.
References _source.
target()
dhyara::peer::address dhyara::packets::echo_request::target () const inline
Target address of the ICMP packet.
Definition at line 74 of file echo_request.h.
References _target.
Referenced by target().
time()
std::uint64_t dhyara::packets::echo_request::time () const inline
Time in the packet.
Definition at line 62 of file echo_request.h.
References _time.
ttl()
std::uint8_t dhyara::packets::echo_request::ttl () const inline
TTL of the ICMP request.
Definition at line 70 of file echo_request.h.
References _ttl.
Member Data Documentation
_seq
std::uint32_t dhyara::packets::echo_request::_seq
Definition at line 30 of file echo_request.h.
Referenced by seq().
_source
raw_address_type dhyara::packets::echo_request::_source
Definition at line 29 of file echo_request.h.
Referenced by source().
_target
raw_address_type dhyara::packets::echo_request::_target
Definition at line 28 of file echo_request.h.
Referenced by target().
_time
std::uint64_t dhyara::packets::echo_request::_time
Definition at line 31 of file echo_request.h.
Referenced by time().
_ttl
std::uint8_t dhyara::packets::echo_request::_ttl
Definition at line 32 of file echo_request.h.
Referenced by ttl().
The documentation for this struct was generated from the following file:
/home/runner/work/dhyara/dhyara/includes/dhyara/packets/echo_request.h