Dhyara: dhyara::packets::data Struct Reference
dhyara::packets::data Struct Reference
Packets
A virtual packet, that is never sent accros the network.
#include <data.h>
Public Types
typedef std::basic_string< std::uint8_t > dynamic_buffer_type
typedef dynamic_buffer_type::const_iterator const_iterator
typedef dynamic_buffer_type::iterator iterator
Public Member Functions
data (const dhyara::peer::address &target, const dhyara::peer::address &source)
Construct a data packet.
data (const dhyara::peer::address &target, std::uint8_t packet)
Construct a data packet.
data (const dhyara::peer::address &target)
Construct a data packet.
data (const dhyara::peer::address &target, const dhyara::peer::address &source, std::uint8_t packet)
Construct a data packet.
template<typename InputIt >
data (const dhyara::peer::address &target, InputIt begin, InputIt end)
Construct a data packet by iterating over.
dhyara::peer::address target () const
target of the data packet
dhyara::peer::address source () const
source of the data packet
std::uint8_t id () const
packet id of data packet
bool operator< (const data &other) const
Less than comparison operator checks packet id.
std::size_t length () const
length of the data packet
std::uint8_t chunks () const
number of chunks required to send this data packet
chunk prepare (std::uint8_t n) const
Generate the n'th chunk for this data packet.
template<typename InputIt >
void fill (InputIt begin, InputIt end)
Fill the data packet by copying elements within [begin, end) range.
template<typename OutputIt >
void copy (OutputIt it) const
Copy elements of the data packet to the output iterator.
void add (const dhyara::packets::chunk &chunk)
appends a chunk with the data packet
void reserve (std::uint32_t size)
reserve space in the dynamic buffer
const std::uint8_t * raw () const
Returns raw data in the buffer.
const_iterator begin () const
Returns an immutable iterator to the data.
const_iterator end () const
Returns an immutable iterator to the data.
Public Attributes
dhyara::peer::address _target
dhyara::peer::address _source
std::uint8_t _packet
dynamic_buffer_type _buffer
Static Public Attributes
static std::uint8_t counter
Detailed Description
A virtual packet, that is never sent accros the network.
Instead a data packet is splitted into multiple consecutive chunks. However after receiving all chunks of a data packet and data packet is constructed and passed to the appropriate callback.
Note
Every data packet have a packet id, which is included in the delivery report once that data packet reaches its destination.
Definition at line 27 of file data.h.
Member Typedef Documentation
const_iterator
typedef dynamic_buffer_type::const_iterator dhyara::packets::data::const_iterator
Definition at line 29 of file data.h.
dynamic_buffer_type
typedef std::basic_string<std::uint8_t> dhyara::packets::data::dynamic_buffer_type
Definition at line 28 of file data.h.
iterator
typedef dynamic_buffer_type::iterator dhyara::packets::data::iterator
Definition at line 30 of file data.h.
Constructor & Destructor Documentation
data() [1/5]
dhyara::packets::data::data (const dhyara::peer::address & target, const dhyara::peer::address & source) inline
Construct a data packet.
Note
an auto incremented number is used as packet id
Parameters
target target address
source source address
Definition at line 45 of file data.h.
data() [2/5]
dhyara::packets::data::data (const dhyara::peer::address & target, std::uint8_t packet) inline
Construct a data packet.
Parameters
target target address
packet packet id
Definition at line 51 of file data.h.
data() [3/5]
dhyara::packets::data::data (const dhyara::peer::address & target) inline
Construct a data packet.
Note
an auto incremented number is used as packet id
Parameters
target target address
Definition at line 57 of file data.h.
data() [4/5]
dhyara::packets::data::data (const dhyara::peer::address & target, const dhyara::peer::address & source, std::uint8_t packet) inline
Construct a data packet.
Parameters
target target address
source source address
packet packet id
Definition at line 64 of file data.h.
data() [5/5]
template<typename InputIt > dhyara::packets::data::data (const dhyara::peer::address & target, InputIt begin, InputIt end) inline
Construct a data packet by iterating over.
Note
an auto incremented number is used as packet id
Parameters
target target address
begin begin iterator
end end iterator
Definition at line 73 of file data.h.
References begin(), end(), and fill().
Member Function Documentation
add()
void dhyara::packets::data::add (const dhyara::packets::chunk & chunk)
appends a chunk with the data packet
begin()
const_iterator dhyara::packets::data::begin () const inline
Returns an immutable iterator to the data.
The iterator dereferences to std::uint8_t
Definition at line 137 of file data.h.
References _buffer.
Referenced by data(), and fill().
chunks()
std::uint8_t dhyara::packets::data::chunks () const inline
number of chunks required to send this data packet
Definition at line 99 of file data.h.
References dhyara::packets::chunk::capacity, and length().
copy()
template<typename OutputIt > void dhyara::packets::data::copy (OutputIt it) const inline
Copy elements of the data packet to the output iterator.
Parameters
it output iterator
Definition at line 118 of file data.h.
References _buffer.
end()
const_iterator dhyara::packets::data::end () const inline
Returns an immutable iterator to the data.
The iterator dereferences to std::uint8_t
Definition at line 141 of file data.h.
References _buffer.
Referenced by data(), and fill().
fill()
template<typename InputIt > void dhyara::packets::data::fill (InputIt begin, InputIt end) inline
Fill the data packet by copying elements within [begin, end) range.
Parameters
begin begin iterator
end end iterator
Definition at line 110 of file data.h.
References _buffer, begin(), and end().
Referenced by data().
id()
std::uint8_t dhyara::packets::data::id () const inline
packet id of data packet
Definition at line 87 of file data.h.
References _packet.
length()
std::size_t dhyara::packets::data::length () const inline
length of the data packet
Definition at line 95 of file data.h.
References _buffer.
Referenced by chunks().
operator<()
bool dhyara::packets::data::operator< (const data & other) const inline
Less than comparison operator checks packet id.
Definition at line 91 of file data.h.
References _packet.
prepare()
chunk dhyara::packets::data::prepare (std::uint8_t n) const
Generate the n'th chunk for this data packet.
raw()
const std::uint8_t* dhyara::packets::data::raw () const inline
Returns raw data in the buffer.
Definition at line 132 of file data.h.
References _buffer.
reserve()
void dhyara::packets::data::reserve (std::uint32_t size)
reserve space in the dynamic buffer
source()
dhyara::peer::address dhyara::packets::data::source () const inline
source of the data packet
Definition at line 83 of file data.h.
References _source.
target()
dhyara::peer::address dhyara::packets::data::target () const inline
target of the data packet
Definition at line 79 of file data.h.
References _target.
Member Data Documentation
_buffer
dynamic_buffer_type dhyara::packets::data::_buffer
Definition at line 35 of file data.h.
Referenced by begin(), copy(), end(), fill(), length(), and raw().
_packet
std::uint8_t dhyara::packets::data::_packet
Definition at line 34 of file data.h.
Referenced by id(), and operator<().
_source
dhyara::peer::address dhyara::packets::data::_source
Definition at line 33 of file data.h.
Referenced by source().
_target
dhyara::peer::address dhyara::packets::data::_target
Definition at line 32 of file data.h.
Referenced by target().
counter
std::uint8_t dhyara::packets::data::counter static
Definition at line 37 of file data.h.
The documentation for this struct was generated from the following file:
includes/dhyara/packets/data.h